var backOnTrackPopup = document.createElement("DIV");
backOnTrackPopup.style.height = "100px";
backOnTrackPopup.style.width = "200px";
backOnTrackPopup.style.backgroundColor = "#FF00FF";
backOnTrackPopup.style.zIndex = "100";
backOnTrackPopup.style.position = "fixed";
backOnTrackPopup.style.top = "50px";
backOnTrackPopup.style.left = "45%";
document.body.appendChild(backOnTrackPopup);
console.log("Script was run successfully");